### PR TITLE
Make immovable boxes into walls

### PR DESCRIPTION
**Pull request by Westh**

### CODE REVIEW

**Comment by alexdor** [comment]
Looks good, could you move the waitGroup before the new function and start counting goals before you run the box to wall func ?

**Comment by Westh** [comment]
> Looks good, could you move the waitGroup before the new function and start counting goals before you run the box to wall func ?

Like dis?

**Comment by Westh** [comment]
`SAfootsteps.lvl` is for some reason not being solved... just tried to solve it with the `feat/ma` branch and it also seems to fail there. It might be that we randomly solve it sometimes... Thoughts?

**Comment by alexdor** [comment]
I think it times out, depending on the machine we get from github it will either manage to resolve the lvl in the specified time or not. We could increase the timeout to 220 or smth

**Pull request merged**
